name: Default
priority: 1
count: 0
maps:
- Decay
- Finis
- Ignum
- Wilky Way
- Snowy Frontier
- Garden
- Lagoon
- Government
- Hekla
- Nyah
- Stonehenge
- Downforce
- Command
- Sheol
- Covert Fortress
- Hillside Mini
- Vertex
- "Interitus: Mini"
